version: 1

sources:
  - name: api_ods
    database: dwh
    schema: ods
    tables:
      - name: products
        description: "Немного обработанные данные после экстракции из s3"
  - name: api_dm
    database: dwh
    schema: dm
    tables:
      - name: products
        description: "Подготовленная для аналитики витрина данных по категориям"
